local barrel = peripheral.wrap("back")
local file = io.open("list.lxt", "w")
io.output(file)
local pretty = require("cc.pretty")
local doc = pretty.pretty(barrel.list())
local str = pretty.render(doc, 55)
io.write(str)
io.flush()
io.close(file)
